#---------------------------------------------------
SET(OpenIGTLink_DEPENDENCIES)

#---------------------------------------------------
# VideoStreaming dependencies
IF(BUILD_VIDEOSTREAM)
  IF(USE_H264)
    set(H264_SOURCE_DIR "" CACHE PATH "H264 source directory" FORCE)
		set(H264_LIBRARY_DIR "" CACHE PATH "H264 library directory" FORCE)     
    INCLUDE(${CMAKE_CURRENT_LIST_DIR}/External_openh264.cmake)
  ENDIF()
  
  IF(USE_X265 OR USE_OPENHEVC OR USE_VP9)
		set(YASM_SOURCE_DIR "" CACHE PATH "YASM source directory" FORCE)
		set(YASM_LIBRARY_DIR "" CACHE PATH "YASM library directory" FORCE)
    INCLUDE(${CMAKE_CURRENT_LIST_DIR}/External_yasm.cmake)
    LIST(APPEND OpenIGTLink_DEPENDENCIES yasm)
	ENDIF()

  IF(USE_VP9)
    set(VP9_SOURCE_DIR "" CACHE PATH "VP9 source directory" FORCE)
		set(VP9_LIBRARY_DIR "" CACHE PATH "VP9 library directory" FORCE)
    INCLUDE(${CMAKE_CURRENT_LIST_DIR}/External_VP9.cmake)
    #LIST(APPEND OpenIGTLink_DEPENDENCIES VP9)
  ENDIF()
	
  IF(USE_X265)
    set(X265_SOURCE_DIR "" CACHE PATH "X265 source directory" FORCE)
		set(X265_LIBRARY_DIR "" CACHE PATH "X265 library directory" FORCE)
    INCLUDE(${CMAKE_CURRENT_LIST_DIR}/External_x265.cmake)
    LIST(APPEND OpenIGTLink_DEPENDENCIES x265)
  ENDIF()
  
  IF(USE_OPENHEVC)
 		set(OPENHEVC_SOURCE_DIR "" CACHE PATH "OpenHEVC source directory" FORCE)
		set(OPENHEVC_LIBRARY_DIR "" CACHE PATH "OpenHEVC library directory" FORCE)
    INCLUDE(${CMAKE_CURRENT_LIST_DIR}/External_openHEVC.cmake)
    LIST(APPEND OpenIGTLink_DEPENDENCIES openHEVC)
  ENDIF()

  IF(BUILD_WEBSOCKET)
    INCLUDE(${CMAKE_CURRENT_LIST_DIR}/External_WebSocket.cmake)
    LIST(APPEND OpenIGTLink_DEPENDENCIES websocket)
  ENDIF()
ENDIF()
ExternalProject_Add( OpenIGTLink-lib
	PREFIX "${CMAKE_BINARY_DIR}/OpenIGTLink-prefix"
	SOURCE_DIR "${CMAKE_BINARY_DIR}/OpenIGTLink"
	BINARY_DIR "${CMAKE_BINARY_DIR}/OpenIGTLink-bin"
	#--Download step--------------
	GIT_REPOSITORY "https://github.com/leochan2009/OpenIGTLink.git"
	GIT_TAG superbuild-findmodules
	#--Configure step-------------
	CMAKE_ARGS
		${PLATFORM_SPECIFIC_ARGS}
		-DOpenIGTLink_SUPERBUILD:BOOL=OFF
		-DCMAKE_LIBRARY_OUTPUT_DIRECTORY:STRING=${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
		-DCMAKE_RUNTIME_OUTPUT_DIRECTORY:STRING=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
		-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY:PATH=${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}
		-DBUILD_SHARED_LIBS:BOOL=${OpenIGTLink_BUILD_SHARED_LIBS} 
		-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
		-DBUILD_TESTING:BOOL=${BUILD_TESTING}
		-DUSE_GTEST:BOOL=${USE_GTEST}
		-DBUILD_VIDEOSTREAM:BOOL=${BUILD_VIDEOSTREAM}
		-DUSE_H264:BOOL=${USE_H264}
		-DUSE_VP9:BOOL=${USE_VP9}
		-DUSE_X265:BOOL=${USE_X265}
		-DUSE_OPENHEVC:BOOL=${USE_OPENHEVC}
		-DBUILD_WEBSOCKET:BOOL=${BUILD_WEBSOCKET}
		-DBUILD_EXAMPLES:BOOL=${BUILD_EXAMPLES}
		-DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
		-DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
		-DH264_SOURCE_DIR:STRING=${H264_SOURCE_DIR}
		-DH264_LIBRARY_DIR:STRING=${H264_LIBRARY_DIR}
		-DX265_SOURCE_DIR:STRING=${X265_SOURCE_DIR}
		-DX265_LIBRARY_DIR:STRING=${X265_LIBRARY_DIR}
		-DOPENHEVC_SOURCE_DIR:STRING=${OPENHEVC_SOURCE_DIR}
		-DOPENHEVC_LIBRARY_DIR:STRING=${OPENHEVC_LIBRARY_DIR}
		-DVP9_SOURCE_DIR:STRING=${VP9_SOURCE_DIR}
		-DVP9_LIBRARY_DIR:STRING=${VP9_LIBRARY_DIR}
		-DYASM_SOURCE_DIR:STRING=${YASM_SOURCE_DIR}
		-DYASM_LIBRARY_DIR:STRING=${YASM_LIBRARY_DIR}
	#--Build step-----------------
	BUILD_ALWAYS 1
	#--Install step-----------------
	INSTALL_COMMAND ""
	DEPENDS ${OpenIGTLink_DEPENDENCIES}
	)